site_name: Data Analytics & AI Documentation
# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
    # - content.tabs.link
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    # - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to automatic mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
# Plugins
plugins:
  - blog:
      blog_toc: true
  - tags
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocs-jupyter
  - render_swagger
hooks:
  - pyscripts/authors/authors.py
  - pyscripts/doculabels/doculabels.py

extra:
  authors:
    - Wilsven Leong:
        alias: wilsven
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/64478824?v=4
        url: https://github.com/Wilsven
    - Ong Tsien Jin:
        alias:
          - tsienjin
          - tjay
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/46650957?v=4
        url: https://github.com/TsienJin
    - Lyndon Lim:
        alias: lyndon
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/80683209?v=4
        url: https://github.com/lyndonlim27
    - Ho Si Xian:
        alias: Si Xian
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/60807138?v=4
        url: https://github.com/sixiannn
    - Joycelyn Woo:
        alias: joycelyn
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/139433726?v=4
        url: https://github.com/jwyting
    - Issac J:
        alias: issacj
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/68261814?v=4
        url: https://github.com/issacj-17
    - Jin Chou:
        alias: jinchou
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/74240198?v=4
        url: https://github.com/jinchad

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - styles/mermaid.css
  - styles/author.css
  - styles/doculabels.css

nav:
  - Home:
      - index.md
      - Contribution Guides:
          - home/contribution_guides/introduction.md
          - home/contribution_guides/formatting.md
          - home/contribution_guides/endpoints.md
          - home/contribution_guides/classes_types_and_all.md
      - Hooks:
          - home/hooks/authors.md
          - home/hooks/doculabels.md

  - Projects:
      - GenAI:
          - Health Hub:
              - Data Pipeline:
                  - projects/genai/health-hub/data-pipeline/index.md
                  - projects/genai/health-hub/data-pipeline/introduction.md

              - Clustering Pipeline:
                  - projects/genai/health-hub/clustering-pipeline/introduction.md
                  - Experimentations:
                      - projects/genai/health-hub/clustering-pipeline/experimentations/embedding_techniques/embedding_techniques.md
                      - projects/genai/health-hub/clustering-pipeline/experimentations/multi_feature/multi_feature_clustering_methodology.md
                      - projects/genai/health-hub/clustering-pipeline/experimentations/feature_selection/feature_selection.md
                      - projects/genai/health-hub/clustering-pipeline/experimentations/subclustering/subclustering.md
                  - Nodes:
                      - projects/genai/health-hub/clustering-pipeline/nodes/introduction.md
                      - Node 1:
                          - projects/genai/health-hub/clustering-pipeline/nodes/merge_ground_truth_to_data/merge_ground_truth_to_data.md
                      - Node 2:
                          - projects/genai/health-hub/clustering-pipeline/nodes/generate_cluster/generate_cluster.md
                          - projects/genai/health-hub/clustering-pipeline/nodes/generate_cluster/utils.md
                      - Node 3:
                          - projects/genai/health-hub/clustering-pipeline/nodes/generate_subcluster/generate_subcluster.md
                          - projects/genai/health-hub/clustering-pipeline/nodes/generate_subcluster/utils.md
                      - Node 4:
                          - projects/genai/health-hub/clustering-pipeline/nodes/update_edges_dataframe/update_edges_dataframe.md
                      - Node 5:
                          - projects/genai/health-hub/clustering-pipeline/nodes/cluster_viz/cluster_visualization.md
                      - projects/genai/health-hub/clustering-pipeline/parameters_clustering.md

              - Article Rewriting:
                  - projects/genai/health-hub/article-rewriting/Introduction.md
                  - projects/genai/health-hub/article-rewriting/LangChain.md
                  - projects/genai/health-hub/article-rewriting/LangGraph.md
                  - projects/genai/health-hub/article-rewriting/LLM_Observability.md
                  - Optimisation Checks:
                      - projects/genai/health-hub/article-rewriting/optimisation-checks/Introduction.md

              - Webapp:
                  - projects/genai/health-hub/webapp/introduction.md
                  - Frontend:
                      - projects/genai/health-hub/webapp/frontend/introduction.md
                      - projects/genai/health-hub/webapp/frontend/frontend_activity_diagram.md
                      - Services:
                          - projects/genai/health-hub/webapp/frontend/services/cluster.md
                          - projects/genai/health-hub/webapp/frontend/services/job.md
                          - projects/genai/health-hub/webapp/frontend/services/colour.md
                      - Pipes:
                          - projects/genai/health-hub/webapp/frontend/pipes/date.md
                      - Types:
                          - projects/genai/health-hub/webapp/frontend/types/cluster.md
                          - projects/genai/health-hub/webapp/frontend/types/article.md
                          - projects/genai/health-hub/webapp/frontend/types/edge.md
                          - projects/genai/health-hub/webapp/frontend/types/sorter.md
                          - projects/genai/health-hub/webapp/frontend/types/groups.md
                      - Utilities:
                          - projects/genai/health-hub/webapp/frontend/utilities/group_manager.md
                  - Backend:
                      - projects/genai/health-hub/webapp/backend/introduction.md
                      - projects/genai/health-hub/webapp/system_architecture.md
                      - Types:
                          - projects/genai/health-hub/webapp/backend/types/overview.md
                          - Articles:
                              - projects/genai/health-hub/webapp/backend/types/articles/article.md
                              - projects/genai/health-hub/webapp/backend/types/articles/article_meta.md
                              - projects/genai/health-hub/webapp/backend/types/articles/article_status.md
                              - projects/genai/health-hub/webapp/backend/types/articles/generated_article.md
                          - Relations:
                              - projects/genai/health-hub/webapp/backend/types/relations/group.md
                              - projects/genai/health-hub/webapp/backend/types/relations/edge.md
                          - Jobs:
                              - projects/genai/health-hub/webapp/backend/types/jobs/job.md
                              - projects/genai/health-hub/webapp/backend/types/jobs/job_combine.md
                              - projects/genai/health-hub/webapp/backend/types/jobs/job_ignore.md
                              - projects/genai/health-hub/webapp/backend/types/jobs/job_optimise.md
                              - projects/genai/health-hub/webapp/backend/types/jobs/job_remove.md
                      - API:
                          - projects/genai/health-hub/webapp/backend/api/endpoints.md
                      - Database:
                          - projects/genai/health-hub/webapp/backend/db/db_connector.md
                          - Mongo:
                              - projects/genai/health-hub/webapp/backend/db/mongo/er_diagram.md
                              - projects/genai/health-hub/webapp/backend/db/mongo/mongo_connector.md
                              - projects/genai/health-hub/webapp/backend/db/mongo/beanie_documents.md
                  - Misc:
                      - projects/genai/health-hub/webapp/misc/populator.md
                      - projects/genai/health-hub/webapp/misc/mocker.md

          - Conversational Assistant:
              - Webapp:
                  - Frontend:
                      - projects/genai/conversational-assistant/webapp/frontend/introduction.md
                      - Services:
                          - projects/genai/conversational-assistant/webapp/frontend/services/voice-activity-detection.md
                          - projects/genai/conversational-assistant/webapp/frontend/services/chat-message.md
                          - projects/genai/conversational-assistant/webapp/frontend/services/audio-player.md
                          - projects/genai/conversational-assistant/webapp/frontend/services/endpoint.md
                          - projects/genai/conversational-assistant/webapp/frontend/services/conversation-broker.md
                          - projects/genai/conversational-assistant/webapp/frontend/services/preference.md
                  - Backend:
                      - API:
                          - projects/genai/conversational-assistant/webapp/backend/api/endpoints.md

          - Example Project:
              - Section One:
                  - projects/genai/example-project/section-one/index.md
                  - projects/genai/example-project/section-one/introduction.md
                  - projects/genai/example-project/section-one/tfidf_max_features_384_cosine_emd.ipynb
              - Section Two:
                  - projects/genai/example-project/section-two/index.md
                  - projects/genai/example-project/section-two/introduction.md
  - Articles:
      - blog/index.md
