site_name: Data Analytics & AI Documentation
# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
    # - content.tabs.link
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    # - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to automatic mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
# Plugins
plugins:
  - blog:
      blog_toc: true
  - tags
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocs-jupyter
  - render_swagger
hooks:
  - pyscripts/authors/authors.py
  - pyscripts/doculabels/doculabels.py

extra:
  authors:
    - Wilsven Leong:
        alias: wilsven
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/64478824?v=4
        url: https://github.com/Wilsven
    - Ong Tsien Jin:
        alias:
          - tsienjin
          - tjay
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/46650957?v=4
        url: https://github.com/TsienJin
    - Lyndon Lim:
        alias: lyndon
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/80683209?v=4
        url: https://github.com/lyndonlim27
    - Ho Si Xian:
        alias: Si Xian
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/60807138?v=4
        url: https://github.com/sixiannn
    - Joycelyn Woo:
        alias: joycelyn
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/139433726?v=4
        url: https://github.com/jwyting
    - Issac J:
        alias: issacj
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/68261814?v=4
        url: https://github.com/issacj-17
    - Jin Chou:
        alias: jinchou
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/74240198?v=4
        url: https://github.com/jinchad

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - styles/mermaid.css
  - styles/author.css
  - styles/doculabels.css

nav:
  - Home:
      - index.md
      - Contribution Guides:
          - home/contribution_guides/introduction.md
          - home/contribution_guides/formatting.md
          - home/contribution_guides/endpoints.md
          - home/contribution_guides/classes_types_and_all.md
      - Hooks:
          - home/hooks/authors.md
          - home/hooks/doculabels.md
  - Projects:
      - Computer Vision:
          - Waymo:
              - Data Processing:
                  - projects/computervision/waymo/data-processing/index.md
                  - projects/computervision/waymo/data-processing/introduction.md
      - Generative AI:
          - Content Optimization:
              - Data & Clustering Pipeline:
                  - Data Processing:
                      - projects/genai/health-hub/data-pipeline/data-processing.md
                      - projects/genai/health-hub/data-pipeline/excluded-articles.md
                  - Feature Engineering: projects/genai/health-hub/data-pipeline/feature-engineering.md
                  - Clustering:
                      - projects/genai/health-hub/data-pipeline/clustering/index.md
                      - Experiments:
                          - projects/genai/health-hub/data-pipeline/clustering/experiments/embedding-techniques.md
                          - projects/genai/health-hub/data-pipeline/clustering/experiments/multi-feature-clustering-methodology.md
                          - projects/genai/health-hub/data-pipeline/clustering/experiments/feature-selection.md
                          - projects/genai/health-hub/data-pipeline/clustering/experiments/subclustering.md
                      - Nodes:
                          - projects/genai/health-hub/data-pipeline/clustering/nodes/index.md
                          - projects/genai/health-hub/data-pipeline/clustering/nodes/merge-ground-truth-to-data.md
                          - projects/genai/health-hub/data-pipeline/clustering/nodes/generate-cluster.md
                          - projects/genai/health-hub/data-pipeline/clustering/nodes/generate-subcluster.md
                          - projects/genai/health-hub/data-pipeline/clustering/nodes/update-edges-dataframe.md
                          - projects/genai/health-hub/data-pipeline/clustering/nodes/cluster-visualization.md
                          - Utilities:
                              - projects/genai/health-hub/data-pipeline/clustering/nodes/utilities/utils_clusters.md
                              - projects/genai/health-hub/data-pipeline/clustering/nodes/utilities/utils_subclusters.md
                          - projects/genai/health-hub/data-pipeline/clustering/nodes/parameters-clustering.md
              - Optimization & Generation:
                  - projects/genai/health-hub/content-opt-and-harm/index.md
                  - projects/genai/health-hub/content-opt-and-harm/langchain.md
                  - projects/genai/health-hub/content-opt-and-harm/langgraph.md
                  - projects/genai/health-hub/content-opt-and-harm/llm-observability.md
                  - Article Optimization Check:
                      - projects/genai/health-hub/content-opt-and-harm/article-opt-check/index.md
                      - projects/genai/health-hub/content-opt-and-harm/article-opt-check/nodes/content.md
                      - projects/genai/health-hub/content-opt-and-harm/article-opt-check/nodes/meta-description.md
                      - projects/genai/health-hub/content-opt-and-harm/article-opt-check/nodes/title.md
                  - Article Generation:
                      - projects/genai/health-hub/content-opt-and-harm/article-generation/index.md
                      - Article Optimisation:
                          - Intro to Article Optimisation: projects/genai/health-hub/content-opt-and-harm/article-generation/article_optimisation_intro.md
                          - Article Optimisation Flow:
                              - Step 1. Article Content Preprocessing: projects/genai/health-hub/content-opt-and-harm/article-generation/article_content_preprocessing.md
                              - Step 2. Researcher Node: projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/researcher_node.md
                              - Step 3. Content Guidelines Optimisation: projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/content_guidelines_optimisation.md
                              - Step 4. Writing Optimisation:
                                  - Writing Guidelines Optimisation: projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/writing_guidelines_optimisation.md
                                  - Readability Optimisation: projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/readability_optimisation.md
                                  - Personality Evaluation: projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/personality_evaluation.md
                              - Step 5. Title Optimisation: projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/title_optimisation.md
                              - Step 6. Meta Desc Optimisation: projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/meta_desc_optimisation.md
                      - Article Harmonisation:
                          - Intro to Article Harmonisation Intro: projects/genai/health-hub/content-opt-and-harm/article-generation/article_harmonisation_intro.md
                          - Article Harmonisation Flow:
                              - Step 1. Article Content Preprocessing: projects/genai/health-hub/content-opt-and-harm/article-generation/article_content_preprocessing.md
                              - Step 2. Researcher Node: projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/researcher_node.md
                              - Step 3. Compiler Node: projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/compiler_node.md
                              - Step 4. Content Guidelines Optimisation: projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/content_guidelines_harmonisation.md
                              - Step 5. Writing Optimisation:
                                  - Writing Guidelines Optimisation: projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/writing_guidelines_optimisation.md
                                  - Readability Optimisation: projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/readability_optimisation.md
                                  - Personality Evaluation: projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/personality_evaluation.md
                              - Step 6. Title Optimisation: projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/title_optimisation.md
                              - Step 7. Meta Desc Optimisation: projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/meta_desc_optimisation.md

              - Webapp (Deprecated):
                  - projects/genai/health-hub/webapp/index.md
                  - Frontend:
                      - projects/genai/health-hub/webapp/frontend/index.md
                      - projects/genai/health-hub/webapp/frontend/frontend-activity-diagram.md
                      - Services:
                          - projects/genai/health-hub/webapp/frontend/services/cluster.md
                          - projects/genai/health-hub/webapp/frontend/services/job.md
                          - projects/genai/health-hub/webapp/frontend/services/colour.md
                      - Pipes:
                          - projects/genai/health-hub/webapp/frontend/pipes/date.md
                      - Types:
                          - projects/genai/health-hub/webapp/frontend/types/cluster.md
                          - projects/genai/health-hub/webapp/frontend/types/article.md
                          - projects/genai/health-hub/webapp/frontend/types/edge.md
                          - projects/genai/health-hub/webapp/frontend/types/sorter.md
                          - projects/genai/health-hub/webapp/frontend/types/groups.md
                      - Utilities:
                          - projects/genai/health-hub/webapp/frontend/utilities/group-manager.md
                  - Backend:
                      - projects/genai/health-hub/webapp/backend/index.md
                      - projects/genai/health-hub/webapp/system-architecture.md
                      - Types:
                          - projects/genai/health-hub/webapp/backend/types/overview.md
                          - Articles:
                              - projects/genai/health-hub/webapp/backend/types/articles/article.md
                              - projects/genai/health-hub/webapp/backend/types/articles/article-meta.md
                              - projects/genai/health-hub/webapp/backend/types/articles/article-status.md
                              - projects/genai/health-hub/webapp/backend/types/articles/generated-article.md
                          - Relations:
                              - projects/genai/health-hub/webapp/backend/types/relations/group.md
                              - projects/genai/health-hub/webapp/backend/types/relations/edge.md
                          - Jobs:
                              - projects/genai/health-hub/webapp/backend/types/jobs/job.md
                              - projects/genai/health-hub/webapp/backend/types/jobs/job-combine.md
                              - projects/genai/health-hub/webapp/backend/types/jobs/job-ignore.md
                              - projects/genai/health-hub/webapp/backend/types/jobs/job-optimise.md
                              - projects/genai/health-hub/webapp/backend/types/jobs/job-remove.md
                      - API:
                          - projects/genai/health-hub/webapp/backend/api/endpoints.md
                      - Database:
                          - projects/genai/health-hub/webapp/backend/db/db-connector.md
                          - Mongo:
                              - projects/genai/health-hub/webapp/backend/db/mongo/er-diagram.md
                              - projects/genai/health-hub/webapp/backend/db/mongo/mongo-connector.md
                              - projects/genai/health-hub/webapp/backend/db/mongo/beanie-documents.md
                  - Misc:
                      - projects/genai/health-hub/webapp/misc/populator.md
                      - projects/genai/health-hub/webapp/misc/mocker.md

          - Conversational Assistant:
              - Webapp:
                  - Frontend:
                      - projects/genai/conversational-assistant/webapp/frontend/index.md
                      - Services:
                          - projects/genai/conversational-assistant/webapp/frontend/services/voice-activity-detection.md
                          - projects/genai/conversational-assistant/webapp/frontend/services/chat-message.md
                          - projects/genai/conversational-assistant/webapp/frontend/services/audio-player.md
                          - projects/genai/conversational-assistant/webapp/frontend/services/endpoint.md
                          - projects/genai/conversational-assistant/webapp/frontend/services/conversation-broker.md
                          - projects/genai/conversational-assistant/webapp/frontend/services/preference.md
                  - Backend:
                      - API:
                          - projects/genai/conversational-assistant/webapp/backend/api/endpoints.md
  - Articles:
      - blog/index.md
