name: Lint and Check

on:
  pull_request:
    paths:
      - "**/*.py"
      - "**/*.ipynb"

jobs:
  lint_and_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Cache Python Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort==5.13.2 nbqa==1.8.5 black==24.4.2 black[jupyter]==24.4.2 click==8.1.7 ruff==0.4.9

      - name: Run isort Check
        run: |
          isort --check --profile black .
          nbqa isort . --check --profile black

      - name: Run black Check
        run: |
          black --check --verbose .
          nbqa black . --check --verbose

      - name: Run Ruff Check
        run: ruff check .
